/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_BRAKELIGHTRIGHTACTIVE_H_
#define	_BRAKELIGHTRIGHTACTIVE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BRAKELIGHTRIGHTACTIVE {
	BRAKELIGHTRIGHTACTIVE_off	= 0,
	BRAKELIGHTRIGHTACTIVE_on	= 1
} e_BRAKELIGHTRIGHTACTIVE;

/* BRAKELIGHTRIGHTACTIVE */
typedef long	 BRAKELIGHTRIGHTACTIVE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BRAKELIGHTRIGHTACTIVE;
asn_struct_free_f BRAKELIGHTRIGHTACTIVE_free;
asn_struct_print_f BRAKELIGHTRIGHTACTIVE_print;
asn_constr_check_f BRAKELIGHTRIGHTACTIVE_constraint;
ber_type_decoder_f BRAKELIGHTRIGHTACTIVE_decode_ber;
der_type_encoder_f BRAKELIGHTRIGHTACTIVE_encode_der;
xer_type_decoder_f BRAKELIGHTRIGHTACTIVE_decode_xer;
xer_type_encoder_f BRAKELIGHTRIGHTACTIVE_encode_xer;
per_type_decoder_f BRAKELIGHTRIGHTACTIVE_decode_uper;
per_type_encoder_f BRAKELIGHTRIGHTACTIVE_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BRAKELIGHTRIGHTACTIVE_H_ */
#include <asn_internal.h>
