/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_BreakPadelSwtichSts_H_
#define	_BreakPadelSwtichSts_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BreakPadelSwtichSts {
	BreakPadelSwtichSts_brakepedalnotactive	= 0,
	BreakPadelSwtichSts_brakepedalactive	= 1
} e_BreakPadelSwtichSts;

/* BreakPadelSwtichSts */
typedef long	 BreakPadelSwtichSts_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BreakPadelSwtichSts;
asn_struct_free_f BreakPadelSwtichSts_free;
asn_struct_print_f BreakPadelSwtichSts_print;
asn_constr_check_f BreakPadelSwtichSts_constraint;
ber_type_decoder_f BreakPadelSwtichSts_decode_ber;
der_type_encoder_f BreakPadelSwtichSts_encode_der;
xer_type_decoder_f BreakPadelSwtichSts_decode_xer;
xer_type_encoder_f BreakPadelSwtichSts_encode_xer;
per_type_decoder_f BreakPadelSwtichSts_decode_uper;
per_type_encoder_f BreakPadelSwtichSts_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BreakPadelSwtichSts_H_ */
#include <asn_internal.h>
