/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "V2xBsmRequest"
 * 	found in "V2xBsmRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_BsmOrJam_H_
#define	_BsmOrJam_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BsmOrJam {
	BsmOrJam_bsm	= 0,
	BsmOrJam_jam	= 1
} e_BsmOrJam;

/* BsmOrJam */
typedef long	 BsmOrJam_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BsmOrJam;
asn_struct_free_f BsmOrJam_free;
asn_struct_print_f BsmOrJam_print;
asn_constr_check_f BsmOrJam_constraint;
ber_type_decoder_f BsmOrJam_decode_ber;
der_type_encoder_f BsmOrJam_encode_der;
xer_type_decoder_f BsmOrJam_decode_xer;
xer_type_encoder_f BsmOrJam_encode_xer;
per_type_decoder_f BsmOrJam_decode_uper;
per_type_encoder_f BsmOrJam_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BsmOrJam_H_ */
#include <asn_internal.h>
