/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DemoRequest"
 * 	found in "DemoRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DemoRequestBody_H_
#define	_DemoRequestBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <VisibleString.h>
#include "TIMESTAMP.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DemoRequestBody */
typedef struct DemoRequestBody {
	long	 height;
	VisibleString_t	 width;
	TIMESTAMP_t	 timestamp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DemoRequestBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DemoRequestBody;

#ifdef __cplusplus
}
#endif

#endif	/* _DemoRequestBody_H_ */
#include <asn_internal.h>
