/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DOUBLE_H_
#define	_DOUBLE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DOUBLE */
typedef double	 DOUBLE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DOUBLE;
asn_struct_free_f DOUBLE_free;
asn_struct_print_f DOUBLE_print;
asn_constr_check_f DOUBLE_constraint;
ber_type_decoder_f DOUBLE_decode_ber;
der_type_encoder_f DOUBLE_encode_der;
xer_type_decoder_f DOUBLE_decode_xer;
xer_type_encoder_f DOUBLE_encode_xer;
per_type_decoder_f DOUBLE_decode_uper;
per_type_encoder_f DOUBLE_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DOUBLE_H_ */
#include <asn_internal.h>
