/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ESPAEBactive_H_
#define	_ESPAEBactive_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ESPAEBactive {
	ESPAEBactive_inactive	= 0,
	ESPAEBactive_active	= 1
} e_ESPAEBactive;

/* ESPAEBactive */
typedef long	 ESPAEBactive_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESPAEBactive;
asn_struct_free_f ESPAEBactive_free;
asn_struct_print_f ESPAEBactive_print;
asn_constr_check_f ESPAEBactive_constraint;
ber_type_decoder_f ESPAEBactive_decode_ber;
der_type_encoder_f ESPAEBactive_encode_der;
xer_type_decoder_f ESPAEBactive_decode_xer;
xer_type_encoder_f ESPAEBactive_encode_xer;
per_type_decoder_f ESPAEBactive_decode_uper;
per_type_encoder_f ESPAEBactive_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ESPAEBactive_H_ */
#include <asn_internal.h>
