/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_HornStatus_H_
#define	_HornStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HornStatus {
	HornStatus_unavailable	= 0,
	HornStatus_off	= 1,
	HornStatus_on	= 2
} e_HornStatus;

/* HornStatus */
typedef long	 HornStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HornStatus;
asn_struct_free_f HornStatus_free;
asn_struct_print_f HornStatus_print;
asn_constr_check_f HornStatus_constraint;
ber_type_decoder_f HornStatus_decode_ber;
der_type_encoder_f HornStatus_encode_der;
xer_type_decoder_f HornStatus_decode_xer;
xer_type_encoder_f HornStatus_encode_xer;
per_type_decoder_f HornStatus_decode_uper;
per_type_encoder_f HornStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HornStatus_H_ */
#include <asn_internal.h>
