/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Light_H_
#define	_Light_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TIMESTAMP.h"
#include "TURNINGLAMPSWITCH.h"
#include "EXTERIORLAMPSWITCH.h"
#include "FOGLAMPSWITCH.h"
#include "TELLTALEFRONTFOGLIGHT.h"
#include "TELLTALEREARFOGLIGHT.h"
#include "LOWBEAMINDICATOR.h"
#include "HIGHBEAMINDICATOR.h"
#include "BRAKELIGHTRIGHTACTIVE.h"
#include "BRAKELIGHTLEFTACTIVE.h"
#include "PARKLIGHTONWARNING.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Light */
typedef struct Light {
	MsgCount_t	 msgCnt;
	TIMESTAMP_t	 timeStamp;
	TURNINGLAMPSWITCH_t	 turningLampSwitch;
	EXTERIORLAMPSWITCH_t	 exexteriorLampSwitch;
	FOGLAMPSWITCH_t	 foglampSwitch;
	TELLTALEFRONTFOGLIGHT_t	 telltaleFrontFoglight;
	TELLTALEREARFOGLIGHT_t	 telltaleRearFoglight;
	LOWBEAMINDICATOR_t	 lowBeamIndicator;
	HIGHBEAMINDICATOR_t	 highBeamIndiator;
	BRAKELIGHTRIGHTACTIVE_t	 brakeLightRightActive;
	BRAKELIGHTLEFTACTIVE_t	 brakeLightLeftActive;
	PARKLIGHTONWARNING_t	 parkLightOnWarning;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Light_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Light;

#ifdef __cplusplus
}
#endif

#endif	/* _Light_H_ */
#include <asn_internal.h>
