/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LightList_H_
#define	_LightList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Light;

/* LightList */
typedef struct LightList {
	A_SEQUENCE_OF(struct Light) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LightList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LightList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Light.h"

#endif	/* _LightList_H_ */
#include <asn_internal.h>
