/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TCUTGSMode_H_
#define	_TCUTGSMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCUTGSMode {
	TCUTGSMode_normal	= 0,
	TCUTGSMode_winter	= 1,
	TCUTGSMode_performance	= 2,
	TCUTGSMode_econonmy	= 3,
	TCUTGSMode_inalid	= 4
} e_TCUTGSMode;

/* TCUTGSMode */
typedef long	 TCUTGSMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCUTGSMode;
asn_struct_free_f TCUTGSMode_free;
asn_struct_print_f TCUTGSMode_print;
asn_constr_check_f TCUTGSMode_constraint;
ber_type_decoder_f TCUTGSMode_decode_ber;
der_type_encoder_f TCUTGSMode_encode_der;
xer_type_decoder_f TCUTGSMode_decode_xer;
xer_type_encoder_f TCUTGSMode_encode_xer;
per_type_decoder_f TCUTGSMode_decode_uper;
per_type_encoder_f TCUTGSMode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TCUTGSMode_H_ */
#include <asn_internal.h>
