/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TELLTALEREARFOGLIGHT_H_
#define	_TELLTALEREARFOGLIGHT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TELLTALEREARFOGLIGHT {
	TELLTALEREARFOGLIGHT_notactive	= 0,
	TELLTALEREARFOGLIGHT_active	= 1
} e_TELLTALEREARFOGLIGHT;

/* TELLTALEREARFOGLIGHT */
typedef long	 TELLTALEREARFOGLIGHT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TELLTALEREARFOGLIGHT;
asn_struct_free_f TELLTALEREARFOGLIGHT_free;
asn_struct_print_f TELLTALEREARFOGLIGHT_print;
asn_constr_check_f TELLTALEREARFOGLIGHT_constraint;
ber_type_decoder_f TELLTALEREARFOGLIGHT_decode_ber;
der_type_encoder_f TELLTALEREARFOGLIGHT_encode_der;
xer_type_decoder_f TELLTALEREARFOGLIGHT_decode_xer;
xer_type_encoder_f TELLTALEREARFOGLIGHT_encode_xer;
per_type_decoder_f TELLTALEREARFOGLIGHT_decode_uper;
per_type_encoder_f TELLTALEREARFOGLIGHT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TELLTALEREARFOGLIGHT_H_ */
#include <asn_internal.h>
