/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VALIDWHEELSPEEDFR_H_
#define	_VALIDWHEELSPEEDFR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VALIDWHEELSPEEDFR {
	VALIDWHEELSPEEDFR_valueok	= 0,
	VALIDWHEELSPEEDFR_valueunreliable	= 1
} e_VALIDWHEELSPEEDFR;

/* VALIDWHEELSPEEDFR */
typedef long	 VALIDWHEELSPEEDFR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VALIDWHEELSPEEDFR;
asn_struct_free_f VALIDWHEELSPEEDFR_free;
asn_struct_print_f VALIDWHEELSPEEDFR_print;
asn_constr_check_f VALIDWHEELSPEEDFR_constraint;
ber_type_decoder_f VALIDWHEELSPEEDFR_decode_ber;
der_type_encoder_f VALIDWHEELSPEEDFR_encode_der;
xer_type_decoder_f VALIDWHEELSPEEDFR_decode_xer;
xer_type_encoder_f VALIDWHEELSPEEDFR_encode_xer;
per_type_decoder_f VALIDWHEELSPEEDFR_decode_uper;
per_type_encoder_f VALIDWHEELSPEEDFR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VALIDWHEELSPEEDFR_H_ */
#include <asn_internal.h>
