/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VALIDVEHICLESPEED_H_
#define	_VALIDVEHICLESPEED_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VALIDVEHICLESPEED {
	VALIDVEHICLESPEED_valueok	= 0,
	VALIDVEHICLESPEED_notused	= 1,
	VALIDVEHICLESPEED_valueunreliable	= 2
} e_VALIDVEHICLESPEED;

/* VALIDVEHICLESPEED */
typedef long	 VALIDVEHICLESPEED_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VALIDVEHICLESPEED;
asn_struct_free_f VALIDVEHICLESPEED_free;
asn_struct_print_f VALIDVEHICLESPEED_print;
asn_constr_check_f VALIDVEHICLESPEED_constraint;
ber_type_decoder_f VALIDVEHICLESPEED_decode_ber;
der_type_encoder_f VALIDVEHICLESPEED_encode_der;
xer_type_decoder_f VALIDVEHICLESPEED_decode_xer;
xer_type_encoder_f VALIDVEHICLESPEED_encode_xer;
per_type_decoder_f VALIDVEHICLESPEED_decode_uper;
per_type_encoder_f VALIDVEHICLESPEED_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VALIDVEHICLESPEED_H_ */
#include <asn_internal.h>
