/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VALIDWHEELSPEEDFL_H_
#define	_VALIDWHEELSPEEDFL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VALIDWHEELSPEEDFL {
	VALIDWHEELSPEEDFL_valueok	= 0,
	VALIDWHEELSPEEDFL_valueunreliable	= 1
} e_VALIDWHEELSPEEDFL;

/* VALIDWHEELSPEEDFL */
typedef long	 VALIDWHEELSPEEDFL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VALIDWHEELSPEEDFL;
asn_struct_free_f VALIDWHEELSPEEDFL_free;
asn_struct_print_f VALIDWHEELSPEEDFL_print;
asn_constr_check_f VALIDWHEELSPEEDFL_constraint;
ber_type_decoder_f VALIDWHEELSPEEDFL_decode_ber;
der_type_encoder_f VALIDWHEELSPEEDFL_encode_der;
xer_type_decoder_f VALIDWHEELSPEEDFL_decode_xer;
xer_type_encoder_f VALIDWHEELSPEEDFL_encode_xer;
per_type_decoder_f VALIDWHEELSPEEDFL_decode_uper;
per_type_encoder_f VALIDWHEELSPEEDFL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VALIDWHEELSPEEDFL_H_ */
#include <asn_internal.h>
