/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VALIDWHEELSPEEDRR_H_
#define	_VALIDWHEELSPEEDRR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VALIDWHEELSPEEDRR {
	VALIDWHEELSPEEDRR_valueok	= 0,
	VALIDWHEELSPEEDRR_valueunreliable	= 1
} e_VALIDWHEELSPEEDRR;

/* VALIDWHEELSPEEDRR */
typedef long	 VALIDWHEELSPEEDRR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VALIDWHEELSPEEDRR;
asn_struct_free_f VALIDWHEELSPEEDRR_free;
asn_struct_print_f VALIDWHEELSPEEDRR_print;
asn_constr_check_f VALIDWHEELSPEEDRR_constraint;
ber_type_decoder_f VALIDWHEELSPEEDRR_decode_ber;
der_type_encoder_f VALIDWHEELSPEEDRR_encode_der;
xer_type_decoder_f VALIDWHEELSPEEDRR_decode_xer;
xer_type_encoder_f VALIDWHEELSPEEDRR_encode_xer;
per_type_decoder_f VALIDWHEELSPEEDRR_decode_uper;
per_type_encoder_f VALIDWHEELSPEEDRR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VALIDWHEELSPEEDRR_H_ */
#include <asn_internal.h>
