/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Wiper_H_
#define	_Wiper_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TIMESTAMP.h"
#include "FRONTWIPERSWITCH.h"
#include "FRONTWIPERINTERMSWITCH.h"
#include "REARWIPER.h"
#include "FRONTWASHINGSWITCH.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Wiper */
typedef struct Wiper {
	MsgCount_t	 msgCnt;
	TIMESTAMP_t	 timeStamp;
	FRONTWIPERSWITCH_t	 frontWiperSwitch;
	FRONTWIPERINTERMSWITCH_t	 frontWiperIntermSwitch;
	REARWIPER_t	 rearWiper;
	FRONTWASHINGSWITCH_t	 frontWashingSwitch;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Wiper_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Wiper;

#ifdef __cplusplus
}
#endif

#endif	/* _Wiper_H_ */
#include <asn_internal.h>
