/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ABSOPERATING_H_
#define	_ABSOPERATING_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ABSOPERATING {
	ABSOPERATING_inactive	= 0,
	ABSOPERATING_active	= 1
} e_ABSOPERATING;

/* ABSOPERATING */
typedef long	 ABSOPERATING_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ABSOPERATING;
asn_struct_free_f ABSOPERATING_free;
asn_struct_print_f ABSOPERATING_print;
asn_constr_check_f ABSOPERATING_constraint;
ber_type_decoder_f ABSOPERATING_decode_ber;
der_type_encoder_f ABSOPERATING_encode_der;
xer_type_decoder_f ABSOPERATING_decode_xer;
xer_type_encoder_f ABSOPERATING_encode_xer;
per_type_decoder_f ABSOPERATING_decode_uper;
per_type_encoder_f ABSOPERATING_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ABSOPERATING_H_ */
#include <asn_internal.h>
