/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_BRAKELIGHTLEFTACTIVE_H_
#define	_BRAKELIGHTLEFTACTIVE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BRAKELIGHTLEFTACTIVE {
	BRAKELIGHTLEFTACTIVE_off	= 0,
	BRAKELIGHTLEFTACTIVE_on	= 1
} e_BRAKELIGHTLEFTACTIVE;

/* BRAKELIGHTLEFTACTIVE */
typedef long	 BRAKELIGHTLEFTACTIVE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BRAKELIGHTLEFTACTIVE;
asn_struct_free_f BRAKELIGHTLEFTACTIVE_free;
asn_struct_print_f BRAKELIGHTLEFTACTIVE_print;
asn_constr_check_f BRAKELIGHTLEFTACTIVE_constraint;
ber_type_decoder_f BRAKELIGHTLEFTACTIVE_decode_ber;
der_type_encoder_f BRAKELIGHTLEFTACTIVE_encode_der;
xer_type_decoder_f BRAKELIGHTLEFTACTIVE_decode_xer;
xer_type_encoder_f BRAKELIGHTLEFTACTIVE_encode_xer;
per_type_decoder_f BRAKELIGHTLEFTACTIVE_decode_uper;
per_type_encoder_f BRAKELIGHTLEFTACTIVE_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BRAKELIGHTLEFTACTIVE_H_ */
#include <asn_internal.h>
