/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DemoRequest"
 * 	found in "DemoRequest.asn"
 * 	`asn1c -gen-PER`
 */

#include "DemoRequestBody.h"

static asn_TYPE_member_t asn_MBR_DemoRequestBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DemoRequestBody, height),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"height"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DemoRequestBody, width),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"width"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DemoRequestBody, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TIMESTAMP,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timestamp"
		},
};
static const ber_tlv_tag_t asn_DEF_DemoRequestBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DemoRequestBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* height */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* width */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timestamp */
};
static asn_SEQUENCE_specifics_t asn_SPC_DemoRequestBody_specs_1 = {
	sizeof(struct DemoRequestBody),
	offsetof(struct DemoRequestBody, _asn_ctx),
	asn_MAP_DemoRequestBody_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DemoRequestBody = {
	"DemoRequestBody",
	"DemoRequestBody",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DemoRequestBody_tags_1,
	sizeof(asn_DEF_DemoRequestBody_tags_1)
		/sizeof(asn_DEF_DemoRequestBody_tags_1[0]), /* 1 */
	asn_DEF_DemoRequestBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_DemoRequestBody_tags_1)
		/sizeof(asn_DEF_DemoRequestBody_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DemoRequestBody_1,
	3,	/* Elements count */
	&asn_SPC_DemoRequestBody_specs_1	/* Additional specs */
};

