/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_FLOAT_H_
#define	_FLOAT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FLOAT */
typedef double	 FLOAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FLOAT;
asn_struct_free_f FLOAT_free;
asn_struct_print_f FLOAT_print;
asn_constr_check_f FLOAT_constraint;
ber_type_decoder_f FLOAT_decode_ber;
der_type_encoder_f FLOAT_encode_der;
xer_type_decoder_f FLOAT_decode_xer;
xer_type_encoder_f FLOAT_encode_xer;
per_type_decoder_f FLOAT_decode_uper;
per_type_encoder_f FLOAT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FLOAT_H_ */
#include <asn_internal.h>
