/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_FOGLAMPSWITCH_H_
#define	_FOGLAMPSWITCH_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FOGLAMPSWITCH {
	FOGLAMPSWITCH_inactive	= 0,
	FOGLAMPSWITCH_rearfog	= 1,
	FOGLAMPSWITCH_frontfog	= 2,
	FOGLAMPSWITCH_bothactive	= 3
} e_FOGLAMPSWITCH;

/* FOGLAMPSWITCH */
typedef long	 FOGLAMPSWITCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FOGLAMPSWITCH;
asn_struct_free_f FOGLAMPSWITCH_free;
asn_struct_print_f FOGLAMPSWITCH_print;
asn_constr_check_f FOGLAMPSWITCH_constraint;
ber_type_decoder_f FOGLAMPSWITCH_decode_ber;
der_type_encoder_f FOGLAMPSWITCH_encode_der;
xer_type_decoder_f FOGLAMPSWITCH_decode_xer;
xer_type_encoder_f FOGLAMPSWITCH_encode_xer;
per_type_decoder_f FOGLAMPSWITCH_decode_uper;
per_type_encoder_f FOGLAMPSWITCH_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FOGLAMPSWITCH_H_ */
#include <asn_internal.h>
