/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_FRONTWIPERSWITCH_H_
#define	_FRONTWIPERSWITCH_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FRONTWIPERSWITCH {
	FRONTWIPERSWITCH_off	= 0,
	FRONTWIPERSWITCH_auto	= 1,
	FRONTWIPERSWITCH_low	= 2,
	FRONTWIPERSWITCH_high	= 3,
	FRONTWIPERSWITCH_mist	= 4
} e_FRONTWIPERSWITCH;

/* FRONTWIPERSWITCH */
typedef long	 FRONTWIPERSWITCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FRONTWIPERSWITCH;
asn_struct_free_f FRONTWIPERSWITCH_free;
asn_struct_print_f FRONTWIPERSWITCH_print;
asn_constr_check_f FRONTWIPERSWITCH_constraint;
ber_type_decoder_f FRONTWIPERSWITCH_decode_ber;
der_type_encoder_f FRONTWIPERSWITCH_encode_der;
xer_type_decoder_f FRONTWIPERSWITCH_decode_xer;
xer_type_encoder_f FRONTWIPERSWITCH_encode_xer;
per_type_decoder_f FRONTWIPERSWITCH_decode_uper;
per_type_encoder_f FRONTWIPERSWITCH_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FRONTWIPERSWITCH_H_ */
#include <asn_internal.h>
