/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Gps3D_H_
#define	_Gps3D_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Latitude.h"
#include "Longitude.h"
#include "Elevation.h"
#include "Speed.h"
#include "Heading.h"
#include "TIMESTAMP.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Gps3D */
typedef struct Gps3D {
	Latitude_t	 latitude;
	Longitude_t	 longitude;
	Elevation_t	*elevation	/* OPTIONAL */;
	Speed_t	*speed	/* OPTIONAL */;
	Heading_t	*heading	/* OPTIONAL */;
	TIMESTAMP_t	*timestamp	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Gps3D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Gps3D;

#ifdef __cplusplus
}
#endif

#endif	/* _Gps3D_H_ */
#include <asn_internal.h>
