/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#include "Gps3D.h"

static asn_TYPE_member_t asn_MBR_Gps3D_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Gps3D, latitude),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Latitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Gps3D, longitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Longitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"longitude"
		},
	{ ATF_POINTER, 4, offsetof(struct Gps3D, elevation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Elevation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"elevation"
		},
	{ ATF_POINTER, 3, offsetof(struct Gps3D, speed),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"speed"
		},
	{ ATF_POINTER, 2, offsetof(struct Gps3D, heading),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Heading,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"heading"
		},
	{ ATF_POINTER, 1, offsetof(struct Gps3D, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TIMESTAMP,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timestamp"
		},
};
static const int asn_MAP_Gps3D_oms_1[] = { 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Gps3D_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Gps3D_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* latitude */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* longitude */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* elevation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* speed */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* heading */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* timestamp */
};
static asn_SEQUENCE_specifics_t asn_SPC_Gps3D_specs_1 = {
	sizeof(struct Gps3D),
	offsetof(struct Gps3D, _asn_ctx),
	asn_MAP_Gps3D_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_Gps3D_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Gps3D = {
	"Gps3D",
	"Gps3D",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Gps3D_tags_1,
	sizeof(asn_DEF_Gps3D_tags_1)
		/sizeof(asn_DEF_Gps3D_tags_1[0]), /* 1 */
	asn_DEF_Gps3D_tags_1,	/* Same as above */
	sizeof(asn_DEF_Gps3D_tags_1)
		/sizeof(asn_DEF_Gps3D_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Gps3D_1,
	6,	/* Elements count */
	&asn_SPC_Gps3D_specs_1	/* Additional specs */
};

