/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_HIGHBEAMINDICATOR_H_
#define	_HIGHBEAMINDICATOR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HIGHBEAMINDICATOR {
	HIGHBEAMINDICATOR_off	= 0,
	HIGHBEAMINDICATOR_on	= 1
} e_HIGHBEAMINDICATOR;

/* HIGHBEAMINDICATOR */
typedef long	 HIGHBEAMINDICATOR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HIGHBEAMINDICATOR;
asn_struct_free_f HIGHBEAMINDICATOR_free;
asn_struct_print_f HIGHBEAMINDICATOR_print;
asn_constr_check_f HIGHBEAMINDICATOR_constraint;
ber_type_decoder_f HIGHBEAMINDICATOR_decode_ber;
der_type_encoder_f HIGHBEAMINDICATOR_encode_der;
xer_type_decoder_f HIGHBEAMINDICATOR_decode_xer;
xer_type_encoder_f HIGHBEAMINDICATOR_encode_xer;
per_type_decoder_f HIGHBEAMINDICATOR_decode_uper;
per_type_encoder_f HIGHBEAMINDICATOR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HIGHBEAMINDICATOR_H_ */
#include <asn_internal.h>
