/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "V2xBsmRequest"
 * 	found in "V2xBsmRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_JamLevel_H_
#define	_JamLevel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* JamLevel */
typedef long	 JamLevel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JamLevel;
asn_struct_free_f JamLevel_free;
asn_struct_print_f JamLevel_print;
asn_constr_check_f JamLevel_constraint;
ber_type_decoder_f JamLevel_decode_ber;
der_type_encoder_f JamLevel_encode_der;
xer_type_decoder_f JamLevel_decode_xer;
xer_type_encoder_f JamLevel_encode_xer;
per_type_decoder_f JamLevel_decode_uper;
per_type_encoder_f JamLevel_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _JamLevel_H_ */
#include <asn_internal.h>
