/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#include "Light.h"

static asn_TYPE_member_t asn_MBR_Light_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Light, msgCnt),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"msgCnt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TIMESTAMP,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeStamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, turningLampSwitch),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TURNINGLAMPSWITCH,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"turningLampSwitch"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, exexteriorLampSwitch),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EXTERIORLAMPSWITCH,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"exexteriorLampSwitch"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, foglampSwitch),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FOGLAMPSWITCH,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"foglampSwitch"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, telltaleFrontFoglight),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TELLTALEFRONTFOGLIGHT,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"telltaleFrontFoglight"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, telltaleRearFoglight),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TELLTALEREARFOGLIGHT,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"telltaleRearFoglight"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, lowBeamIndicator),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LOWBEAMINDICATOR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lowBeamIndicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, highBeamIndiator),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HIGHBEAMINDICATOR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"highBeamIndiator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, brakeLightRightActive),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BRAKELIGHTRIGHTACTIVE,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"brakeLightRightActive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, brakeLightLeftActive),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BRAKELIGHTLEFTACTIVE,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"brakeLightLeftActive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Light, parkLightOnWarning),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PARKLIGHTONWARNING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"parkLightOnWarning"
		},
};
static const ber_tlv_tag_t asn_DEF_Light_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Light_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgCnt */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeStamp */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* turningLampSwitch */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* exexteriorLampSwitch */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* foglampSwitch */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* telltaleFrontFoglight */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* telltaleRearFoglight */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* lowBeamIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* highBeamIndiator */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* brakeLightRightActive */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* brakeLightLeftActive */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* parkLightOnWarning */
};
static asn_SEQUENCE_specifics_t asn_SPC_Light_specs_1 = {
	sizeof(struct Light),
	offsetof(struct Light, _asn_ctx),
	asn_MAP_Light_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Light = {
	"Light",
	"Light",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Light_tags_1,
	sizeof(asn_DEF_Light_tags_1)
		/sizeof(asn_DEF_Light_tags_1[0]), /* 1 */
	asn_DEF_Light_tags_1,	/* Same as above */
	sizeof(asn_DEF_Light_tags_1)
		/sizeof(asn_DEF_Light_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Light_1,
	12,	/* Elements count */
	&asn_SPC_Light_specs_1	/* Additional specs */
};

