/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LOWBEAMINDICATOR_H_
#define	_LOWBEAMINDICATOR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LOWBEAMINDICATOR {
	LOWBEAMINDICATOR_off	= 0,
	LOWBEAMINDICATOR_on	= 1
} e_LOWBEAMINDICATOR;

/* LOWBEAMINDICATOR */
typedef long	 LOWBEAMINDICATOR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LOWBEAMINDICATOR;
asn_struct_free_f LOWBEAMINDICATOR_free;
asn_struct_print_f LOWBEAMINDICATOR_print;
asn_constr_check_f LOWBEAMINDICATOR_constraint;
ber_type_decoder_f LOWBEAMINDICATOR_decode_ber;
der_type_encoder_f LOWBEAMINDICATOR_encode_der;
xer_type_decoder_f LOWBEAMINDICATOR_decode_xer;
xer_type_encoder_f LOWBEAMINDICATOR_encode_xer;
per_type_decoder_f LOWBEAMINDICATOR_decode_uper;
per_type_encoder_f LOWBEAMINDICATOR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LOWBEAMINDICATOR_H_ */
#include <asn_internal.h>
