/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ResponsErrodCode_H_
#define	_ResponsErrodCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResponsErrodCode */
typedef long	 ResponsErrodCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponsErrodCode;
asn_struct_free_f ResponsErrodCode_free;
asn_struct_print_f ResponsErrodCode_print;
asn_constr_check_f ResponsErrodCode_constraint;
ber_type_decoder_f ResponsErrodCode_decode_ber;
der_type_encoder_f ResponsErrodCode_encode_der;
xer_type_decoder_f ResponsErrodCode_decode_xer;
xer_type_encoder_f ResponsErrodCode_encode_xer;
per_type_decoder_f ResponsErrodCode_decode_uper;
per_type_encoder_f ResponsErrodCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponsErrodCode_H_ */
#include <asn_internal.h>
