/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Running_H_
#define	_Running_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TIMESTAMP.h"
#include "BreakPadelSwtichSts.h"
#include <NativeReal.h>
#include "VALIDACCELERATOR.h"
#include "TotalODO.h"
#include "VALIDWHEELSPEEDFL.h"
#include "VALIDWHEELSPEEDFR.h"
#include "VALIDWHEELSPEEDRL.h"
#include "VALIDWHEELSPEEDRR.h"
#include "VALIDVEHICLESPEED.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Running */
typedef struct Running {
	MsgCount_t	 msgCnt;
	TIMESTAMP_t	 timeStamp;
	BreakPadelSwtichSts_t	 bareakPadelSwtichSts;
	double	 battSoc;
	double	 vcu616DriveRange;
	double	 oilLeft;
	double	 longitudinalAcceleration;
	double	 longitudinalOffset;
	double	 lateralAcceleration;
	double	 lateralOffset;
	double	 yawVelocity;
	double	 yawVelocityOffset;
	double	 steeringWheelRotationSpeed;
	double	 steeringWheelAngle;
	VALIDACCELERATOR_t	 validAcceleator;
	double	 acceleratorPos;
	TotalODO_t	 totalOdo;
	VALIDWHEELSPEEDFL_t	 validWheelSpeedFl;
	double	 wheelSpeedFl;
	VALIDWHEELSPEEDFR_t	 validWheelFr;
	double	 wheelSpeedFr;
	VALIDWHEELSPEEDRL_t	 validWheelSpeedRl;
	double	 wheelSpeedRl;
	VALIDWHEELSPEEDRR_t	 validWheelRr;
	double	 wheelSpeedRr;
	VALIDVEHICLESPEED_t	 validVehicleSpeed;
	double	 vehicleSpeed;
	double	 motoSpeed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Running_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Running;

#ifdef __cplusplus
}
#endif

#endif	/* _Running_H_ */
#include <asn_internal.h>
