/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RunningList_H_
#define	_RunningList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Running;

/* RunningList */
typedef struct RunningList {
	A_SEQUENCE_OF(struct Running) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RunningList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RunningList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Running.h"

#endif	/* _RunningList_H_ */
#include <asn_internal.h>
