/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#include "Safety.h"

static asn_TYPE_member_t asn_MBR_Safety_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, msgCnt),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"msgCnt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TIMESTAMP,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeStamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, absOperating),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ABSOPERATING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"absOperating"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, espAebActive),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ESPAEBactive,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"espAebActive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, espOperating),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ESPOPERATING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"espOperating"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, tcsOperating),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TCSOPERATING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tcsOperating"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, epsSta),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EPSSTA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"epsSta"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, tcuTgsmode),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TCUTGSMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tcuTgsmode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Safety, tcuCurrentgearposition),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TCUCurrentGearPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tcuCurrentgearposition"
		},
};
static const ber_tlv_tag_t asn_DEF_Safety_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Safety_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgCnt */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeStamp */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* absOperating */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* espAebActive */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* espOperating */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* tcsOperating */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* epsSta */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* tcuTgsmode */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* tcuCurrentgearposition */
};
static asn_SEQUENCE_specifics_t asn_SPC_Safety_specs_1 = {
	sizeof(struct Safety),
	offsetof(struct Safety, _asn_ctx),
	asn_MAP_Safety_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Safety = {
	"Safety",
	"Safety",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Safety_tags_1,
	sizeof(asn_DEF_Safety_tags_1)
		/sizeof(asn_DEF_Safety_tags_1[0]), /* 1 */
	asn_DEF_Safety_tags_1,	/* Same as above */
	sizeof(asn_DEF_Safety_tags_1)
		/sizeof(asn_DEF_Safety_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Safety_1,
	9,	/* Elements count */
	&asn_SPC_Safety_specs_1	/* Additional specs */
};

