/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Safety_H_
#define	_Safety_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TIMESTAMP.h"
#include "ABSOPERATING.h"
#include "ESPAEBactive.h"
#include "ESPOPERATING.h"
#include "TCSOPERATING.h"
#include "EPSSTA.h"
#include "TCUTGSMode.h"
#include "TCUCurrentGearPosition.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Safety */
typedef struct Safety {
	MsgCount_t	 msgCnt;
	TIMESTAMP_t	 timeStamp;
	ABSOPERATING_t	 absOperating;
	ESPAEBactive_t	 espAebActive;
	ESPOPERATING_t	 espOperating;
	TCSOPERATING_t	 tcsOperating;
	EPSSTA_t	 epsSta;
	TCUTGSMode_t	 tcuTgsmode;
	TCUCurrentGearPosition_t	 tcuCurrentgearposition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Safety_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Safety;

#ifdef __cplusplus
}
#endif

#endif	/* _Safety_H_ */
#include <asn_internal.h>
