/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SmartCanRequestBody_H_
#define	_SmartCanRequestBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "TIMESTAMP.h"
#include <OCTET_STRING.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WiperList;
struct LightList;
struct RunningList;
struct SafetyList;
struct OthersList;

/* SmartCanRequestBody */
typedef struct SmartCanRequestBody {
	MsgCount_t	 msgCnt;
	TIMESTAMP_t	 timestamp;
	OCTET_STRING_t	 vid;
	BOOLEAN_t	 isautoDrive;
	struct WiperList	*wipers	/* OPTIONAL */;
	struct LightList	*lights	/* OPTIONAL */;
	struct RunningList	*runnings	/* OPTIONAL */;
	struct SafetyList	*safetys	/* OPTIONAL */;
	struct OthersList	*others	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SmartCanRequestBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmartCanRequestBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WiperList.h"
#include "LightList.h"
#include "RunningList.h"
#include "SafetyList.h"
#include "OthersList.h"

#endif	/* _SmartCanRequestBody_H_ */
#include <asn_internal.h>
