/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TCSOPERATING_H_
#define	_TCSOPERATING_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCSOPERATING {
	TCSOPERATING_inactive	= 0,
	TCSOPERATING_active	= 1
} e_TCSOPERATING;

/* TCSOPERATING */
typedef long	 TCSOPERATING_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCSOPERATING;
asn_struct_free_f TCSOPERATING_free;
asn_struct_print_f TCSOPERATING_print;
asn_constr_check_f TCSOPERATING_constraint;
ber_type_decoder_f TCSOPERATING_decode_ber;
der_type_encoder_f TCSOPERATING_encode_der;
xer_type_decoder_f TCSOPERATING_decode_xer;
xer_type_encoder_f TCSOPERATING_encode_xer;
per_type_decoder_f TCSOPERATING_decode_uper;
per_type_encoder_f TCSOPERATING_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TCSOPERATING_H_ */
#include <asn_internal.h>
