/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TELLTALEFRONTFOGLIGHT_H_
#define	_TELLTALEFRONTFOGLIGHT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TELLTALEFRONTFOGLIGHT {
	TELLTALEFRONTFOGLIGHT_notactive	= 0,
	TELLTALEFRONTFOGLIGHT_active	= 1
} e_TELLTALEFRONTFOGLIGHT;

/* TELLTALEFRONTFOGLIGHT */
typedef long	 TELLTALEFRONTFOGLIGHT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TELLTALEFRONTFOGLIGHT;
asn_struct_free_f TELLTALEFRONTFOGLIGHT_free;
asn_struct_print_f TELLTALEFRONTFOGLIGHT_print;
asn_constr_check_f TELLTALEFRONTFOGLIGHT_constraint;
ber_type_decoder_f TELLTALEFRONTFOGLIGHT_decode_ber;
der_type_encoder_f TELLTALEFRONTFOGLIGHT_encode_der;
xer_type_decoder_f TELLTALEFRONTFOGLIGHT_decode_xer;
xer_type_encoder_f TELLTALEFRONTFOGLIGHT_encode_xer;
per_type_decoder_f TELLTALEFRONTFOGLIGHT_decode_uper;
per_type_encoder_f TELLTALEFRONTFOGLIGHT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TELLTALEFRONTFOGLIGHT_H_ */
#include <asn_internal.h>
