/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ThrottlePadel_H_
#define	_ThrottlePadel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ThrottlePadel {
	ThrottlePadel_unavailable	= 0,
	ThrottlePadel_off	= 1,
	ThrottlePadel_on	= 2
} e_ThrottlePadel;

/* ThrottlePadel */
typedef long	 ThrottlePadel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThrottlePadel;
asn_struct_free_f ThrottlePadel_free;
asn_struct_print_f ThrottlePadel_print;
asn_constr_check_f ThrottlePadel_constraint;
ber_type_decoder_f ThrottlePadel_decode_ber;
der_type_encoder_f ThrottlePadel_encode_der;
xer_type_decoder_f ThrottlePadel_decode_xer;
xer_type_encoder_f ThrottlePadel_encode_xer;
per_type_decoder_f ThrottlePadel_decode_uper;
per_type_encoder_f ThrottlePadel_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ThrottlePadel_H_ */
#include <asn_internal.h>
