/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SmartCanRequest"
 * 	found in "SmartCanRequest.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VALIDWHEELSPEEDRL_H_
#define	_VALIDWHEELSPEEDRL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VALIDWHEELSPEEDRL {
	VALIDWHEELSPEEDRL_valueok	= 0,
	VALIDWHEELSPEEDRL_valueunreliable	= 1
} e_VALIDWHEELSPEEDRL;

/* VALIDWHEELSPEEDRL */
typedef long	 VALIDWHEELSPEEDRL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VALIDWHEELSPEEDRL;
asn_struct_free_f VALIDWHEELSPEEDRL_free;
asn_struct_print_f VALIDWHEELSPEEDRL_print;
asn_constr_check_f VALIDWHEELSPEEDRL_constraint;
ber_type_decoder_f VALIDWHEELSPEEDRL_decode_ber;
der_type_encoder_f VALIDWHEELSPEEDRL_encode_der;
xer_type_decoder_f VALIDWHEELSPEEDRL_decode_xer;
xer_type_encoder_f VALIDWHEELSPEEDRL_encode_xer;
per_type_decoder_f VALIDWHEELSPEEDRL_decode_uper;
per_type_encoder_f VALIDWHEELSPEEDRL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VALIDWHEELSPEEDRL_H_ */
#include <asn_internal.h>
